version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "extension/deps/openvic-simulation"
      - dependency-name: "scripts"
