name: Release OpenVic
description: Setup, Build, and Release OpenVic

inputs:
  tag-name:
    description: "Name to assign to the tag (default: github.ref)"
    default: ${{ github.ref }}
  target-repo:
    description: Repository to publish this release to
    default: "OpenVic"
  to-ref:
    description: "Tag/Commit to publish this release to (default: github.ref)"
    default: ${{ github.ref }}
  from-ref:
    description: Tag/Commit to source the release notes from
    required: true
  from-tag:
    description: "Tag name being sourced from (default: from-ref)"
    default: ""
  nightly-release:
    description: Whether the release is a nightly build
    default: "false"
  snapshot-release:
    description: Whether the release is a snapshot release
    default: "false"
  latest:
    description: Latest
    default: "false"
  prerelease:
    description: Pre-release
    required: true
  src-token:
    description: Github token for source repository
    required: true
  target-token:
    description: Github token for target repository
    default: ""
  release-name:
    description: Name of release
    default: ""
  godot-executable-url:
    description: The Linux Headless version of Godot that you want to use to export your project.
    required: true
  godot-templates-url:
    description: The link to the `.tpz` archive of export templates.
    required: true

runs:
  using: composite
  steps:
    - name: Setup regex variables
      shell: bash
      run: |
        echo "SEMVER_REGEX=^v(0|[1-9][0-9]*)((\.(0|[1-9][0-9]*)){1,2})(-(alpha|beta|rc)\.([1-9][0-9]*))?$" >> $GITHUB_ENV
        echo "SEMVER_SNAPSHOT_REGEX=^v(0|[1-9][0-9]*)((\.(0|[1-9][0-9]*)){1,2})-(snapshot|snapshot\.dev)\.([1-9][0-9]*)\+([0-9a-fA-F]{40})$" >> $GITHUB_ENV
        echo "SEMVER_NIGHTLY_REGEX=^v(0|[1-9][0-9]*)((\.(0|[1-9][0-9]*)){1,2})-(nightly\.([1-9]([0-9]){3})\.(([0-9]){2})\.(([0-9]){2}))\+([0-9a-fA-F]{40})$" >> $GITHUB_ENV
        echo "SHA_REGEX=^[0-9a-fA-F]{40}$" >> $GITHUB_ENV

    - name: Validate input values
      shell: bash
      env:
        INPUTS_TAG_NAME: ${{ inputs.tag-name }}
        INPUTS_TARGET_REPO: ${{ inputs.target-repo }}
        INPUTS_TO_REF: ${{ inputs.to-ref }}
        INPUTS_FROM_REF: ${{ inputs.from-ref }}
        INPUTS_FROM_TAG: ${{ inputs.from-tag }}
        INPUTS_NIGHTLY_RELEASE: ${{ inputs.nightly-release }}
        INPUTS_SNAPSHOT_RELEASE: ${{ inputs.snapshot-release }}
        INPUTS_LATEST: ${{ inputs.latest }}
        INPUTS_PRERELEASE: ${{ inputs.prerelease }}
        INPUTS_SRC_TOKEN: ${{ inputs.src-token }}
        INPUTS_TARGET_TOKEN: ${{ inputs.target-token }}
      run: |
        # Can report error for every validation check
        EXIT_STATUS=0

        validate_non_empty () {
          [[ -n ${1-} ]] && return
          echo "::error::${2-parameter} is empty."
          EXIT_STATUS=1
          false
        }

        validate_semver () {
          if validate_non_empty "$1" "${2-}"; then
            [[ ${1-} =~ $SEMVER_REGEX ]] && return
            [[ ${1-} =~ $SEMVER_SNAPSHOT_REGEX ]] && return
            [[ ${1-} =~ $SEMVER_NIGHTLY_REGEX ]] && return
          fi

          if [[ -n ${2-} ]]; then
            echo "::error::$2 is not a valid semver string for versioning starting with v. Valid prerelease values are 'alpha', 'beta', 'rc', 'snapshot', 'snapshot.dev', and 'nightly'. A count value must follow all but 'nightly' prerelease tags, starting from 1. 'nightly' must include the date in YYYY.MM.DD format. 'snapshot', 'snapshot.dev', 'nightly' must include the full commit SHA as a build string."
            EXIT_STATUS=1
          fi
          false
        }

        validate_ref () {
          local VALUE=${1#'refs/tags/'}

          if validate_non_empty "$VALUE" "${2-}"; then
            validate_semver "$VALUE" && return
            [[ ${VALUE:-} =~ $SHA_REGEX ]] && return
          fi

          echo "::error::${2-parameter} is not a git commit SHA or valid semver string for versioning starting with v. Valid prerelease values are 'alpha', 'beta', 'rc', 'snapshot', 'snapshot.dev', and 'nightly'. A count value must follow all but 'nightly' prerelease tags, starting from 1. 'nightly' must include the date in YYYY.MM.DD format. 'snapshot', 'snapshot.dev', 'nightly' must include the full commit SHA as a build string."
          EXIT_STATUS=1
          false
        }

        if [[ $INPUTS_TAG_NAME == refs/tags/* ]]; then
          INPUTS_TAG_NAME=${INPUTS_TAG_NAME#'refs/tags/'}
        fi

        validate_semver "$INPUTS_TAG_NAME" "inputs.tag-name"

        if [[ "$GITHUB_REPOSITORY_OWNER/$INPUTS_TARGET_REPO" != $GITHUB_REPOSITORY ]]; then
          if ! validate_non_empty "$INPUTS_TARGET_REPO" "inputs.target-repo" && [[ -z $INPUTS_TARGET_TOKEN ]]; then
            echo "::error::inputs.target-repo is set to a different repository and the inputs.target-token is not set."
            EXIT_STATUS=1
          fi
        fi

        validate_ref "$INPUTS_TO_REF" "inputs.to-ref"

        validate_ref "$INPUTS_FROM_REF" "inputs.from-ref"

        if [[ -n $INPUTS_FROM_TAG ]]; then
          validate_ref "$INPUTS_FROM_TAG" "inputs.from-tag"
        fi

        validate_non_empty "$INPUTS_SRC_TOKEN" "inputs.src-token"

        exit $EXIT_STATUS

    - name: Copy src-token to env.TARGET_TOKEN
      if: format('{0}/{1}', github.repository_owner, inputs.target-repo) == github.repository
      shell: bash
      env:
        INPUTS_SRC_TOKEN: ${{ inputs.src-token }}
      run: echo "TARGET_TOKEN=$INPUTS_SRC_TOKEN" >> $GITHUB_ENV

    - name: Copy target-token to env.TARGET_TOKEN
      if: format('{0}/{1}', github.repository_owner, inputs.target-repo) != github.repository
      shell: bash
      env:
        INPUTS_TARGET_TOKEN: ${{ inputs.target-token }}
      run: echo "TARGET_TOKEN=$INPUTS_TARGET_TOKEN" >> $GITHUB_ENV

    - name: Set TO_TAG from to-ref
      if: inputs.tag-name == inputs.to-ref
      shell: bash
      env:
        INPUTS_TO_REF: ${{ inputs.to-ref }}
      run: echo "TO_TAG=${INPUTS_TO_REF#'refs/tags/'}" >> $GITHUB_ENV

    - name: Set TO_TAG from tag-name
      if: inputs.tag-name != inputs.to-ref
      shell: bash
      env:
        INPUTS_TAG_NAME: ${{ inputs.tag-name }}
      run: echo "TO_TAG=$INPUTS_TAG_NAME" >> $GITHUB_ENV

    - name: Build Release Notes
      if: inputs.snapshot-release == 'false' && inputs.nightly-release == 'false'
      uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
      env:
        GITHUB_TOKEN: ${{ inputs.src-token }}
      with:
        configuration: "${{ github.action_path }}/release-notes-configuration.json"
        toTag: ${{ inputs.tag-name == inputs.to-ref && env.TO_TAG || inputs.to-ref }}
        fromTag: ${{ inputs.from-ref }}
        outputFile: release-notes.md

    - name: Build Snapshot Release Notes
      if: inputs.snapshot-release == 'true' && inputs.nightly-release == 'false'
      uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
      env:
        GITHUB_TOKEN: ${{ inputs.src-token }}
      with:
        configuration: "${{ github.action_path }}/snapshot-release-notes-configuration.json"
        toTag: ${{ inputs.tag-name == inputs.to-ref && env.TO_TAG || inputs.to-ref }}
        fromTag: ${{ inputs.from-ref }}
        outputFile: release-notes.md

    - name: Build Nightly Release Notes
      if: inputs.nightly-release == 'true' && inputs.snapshot-release == 'false'
      uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
      env:
        GITHUB_TOKEN: ${{ inputs.src-token }}
      with:
        configuration: "${{ github.action_path }}/nightly-release-notes-configuration.json"
        toTag: ${{ inputs.tag-name == inputs.to-ref && env.TO_TAG || inputs.to-ref }}
        fromTag: ${{ inputs.from-ref }}
        outputFile: release-notes.md

    - name: Create release tag and name and set release name in release-notes.md
      shell: bash
      env:
        INPUTS_RELEASE_NAME: ${{ inputs.release-name }}
        INPUTS_FROM_TAG_OR_FROM_REF: ${{ inputs.from-tag || inputs.from-ref }}
      run: |
        if [[ $TO_TAG =~ $SEMVER_REGEX ]]; then
          PRERELEASE_TYPE=${BASH_REMATCH[6]}
          PRERELEASE_VERSION=${BASH_REMATCH[7]}

          if [[ $PRERELEASE_TYPE == 'rc' ]]; then
            PRERELEASE_NAME="Release Candidate"
          else
            PRERELEASE_NAME=${PRERELEASE_TYPE@u}
          fi

          PRERELEASE_VERSION_DATE=$PRERELEASE_VERSION
        elif [[ $TO_TAG =~ $SEMVER_SNAPSHOT_REGEX ]]; then
          PRERELEASE_TYPE=${BASH_REMATCH[5]}
          PRERELEASE_VERSION=${BASH_REMATCH[6]}
          PRERELEASE_HASH=${BASH_REMATCH[7]}

          if [[ $PRERELEASE_TYPE == 'snapshot.dev' ]]; then
            PRERELEASE_NAME="Dev Snapshot"
          else
            PRERELEASE_NAME=${PRERELEASE_TYPE@u}
          fi

          PRERELEASE_VERSION_DATE=$PRERELEASE_VERSION
        elif [[ $TO_TAG =~ $SEMVER_NIGHTLY_REGEX ]]; then
          PRERELEASE_TYPE=nightly
          PRERELEASE_YEAR=${BASH_REMATCH[6]}
          PRERELEASE_MONTH=${BASH_REMATCH[8]}
          PRERELEASE_DAY=${BASH_REMATCH[10]}
          PRERELEASE_HASH=${BASH_REMATCH[12]}
          PRERELEASE_NAME=${PRERELEASE_TYPE@u}

          PRERELEASE_VERSION_DATE="$PRERELEASE_YEAR.$PRERELEASE_MONTH.$PRERELEASE_DAY"
        fi

        VERSION_CORE="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"

        RELEASE_VERSION_INFO="$(xargs <<< "$VERSION_CORE $PRERELEASE_NAME $PRERELEASE_VERSION_DATE")"
        RELEASE_NAME="$RELEASE_VERSION_INFO"
        FULL_RELEASE_NAME="$(basename "$GITHUB_REPOSITORY") $RELEASE_NAME"

        if [[ -n $INPUTS_RELEASE_NAME ]]; then
          RELEASE_NAME="$INPUTS_RELEASE_NAME"
          FULL_RELEASE_NAME="$(basename "$GITHUB_REPOSITORY") $INPUTS_RELEASE_NAME ($RELEASE_VERSION_INFO)"
        fi

        echo "FULL_RELEASE_NAME=$FULL_RELEASE_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

        # Keep up to date with .github/actions/openvic-release release-notes configs
        sed -i "s/<<RELEASE_NAME_REPLACEMENT>>/$FULL_RELEASE_NAME/g" release-notes.md
        sed -i "s/<<FROM_TAG_NAME_REPLACEMENT>>/$INPUTS_FROM_TAG_OR_FROM_REF/g" release-notes.md

        if [[ $INPUTS_FROM_TAG_OR_FROM_REF =~ $SHA_REGEX ]]; then
          RELEASE_OR_COMMIT_PATH=commit
        else
          RELEASE_OR_COMMIT_PATH=releases\\/tag
        fi

        sed -i "s/<<RELEASE_OR_COMMIT_PATH>>/$RELEASE_OR_COMMIT_PATH/g" release-notes.md

    - name: Replace <<REPO>> in release-notes.md
      shell: bash
      run: sed -i "s/<<REPO>>/$(sed 's;\/;\\\/;g' <<< "$GITHUB_REPOSITORY")/g" release-notes.md

    - name: Make library directory
      shell: sh
      run: mkdir "$GITHUB_WORKSPACE/library/"

    - name: Download extension assets
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: game/bin/openvic
        pattern: ${{ github.event.repository.name }}-*-extension
        merge-multiple: true

    - name: Export game
      id: export_game
      uses: ./.github/actions/openvic-export
      with:
        godot-executable-url: ${{ inputs.godot-executable-url}}
        godot-templates-url: ${{ inputs.godot-templates-url }}
        archive-output: true

    - name: Zip extension assets
      uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 # v0.7.6
      with:
        type: "zip"
        filename: libopenvic.zip
        path: game/bin/openvic

    - name: Create and upload asset
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        allowUpdates: true
        artifacts: "${{ steps.export_game.outputs.archive-directory }}/*,libopenvic.zip"
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        name: "${{ env.RELEASE_NAME || '' }}"
        tag: "${{ env.TO_TAG || '' }}"
        commit: "${{ format('{0}/{1}', github.repository_owner, inputs.target-repo) == github.repository && !contains(inputs.to-ref, '.') && inputs.to-ref || '' }}"
        bodyFile: "release-notes.md"
        makeLatest: ${{ inputs.latest }}
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.snapshot-release == 'false' && inputs.nightly-release == 'false' }}
        repo: "${{ inputs.target-repo }}"
        token: ${{ env.TARGET_TOKEN }}
