name: Bug Report
description: "File a bug report. NOTE: Not for reporting distinctions from Victoria II."
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report!

        When reporting a bug, please follow the guidelines in this template. This helps us quickly identify the problem you're having.
        - If this report is about a feature or behavior in Victoria II that is missing or working incorrectly in OpenVic, please report a [Victoria II discrepancy](https://github.com/OpenVicProject/OpenVic/issues/new?assignees=&labels=&projects=&template=2-victoria-2-discrepancy.yml) instead.
        - Write a descriptive issue title above.
        - **Always open *one* issue for *one* bug**. If you notice several bugs, make sure to create one new issue for each of them.
        - Verify that you are using either the latest release or the latest commit. It is preferred that you check if your issue is reproducible in the latest commit - it may already have been fixed!
        - If you're playing with custom source modifications, please test if your bug is reproducible in the latest official build of OpenVic before opening an issue here.

  - type: checkboxes
    attributes:
      label: Duplicate Issue?
      description: "Search [open](https://github.com/OpenVicProject/OpenVic/issues) and [closed](https://github.com/OpenVicProject/OpenVic/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported. If you don't find a relevant match or if you're not sure, don't hesitate to **open a new issue**. Contributors will handle it from there if it's a duplicate."
      options:
      - label: I have checked for an existing bug report.
        required: true

  - type: textarea
    id: game-versions
    attributes:
      label: Game & Version Info
      description: |
        Enter the OpenVic version and commit you found the bug on in this box. You can find and copy this by clicking on the "Game Info" button in the bottom left corner of the OpenVic main menu. If you've found this bug to be reproducible on multiple versions, list all of those versions here.
      placeholder: |
        - Found in: <v0.02_Mappa_Mundi> (c65b2a795fd35e81f7a1906d07d15c47cd94cf9c).
        - Not reproducible in: <v0.01_Primum_Mobile> (1980012045ea4c6b314d6d12a796eda23ae8d7fa).
    validations:
      required: true

  - type: textarea
    id: modlist
    attributes:
      label: Mods or Extensions used
      description: |
        If you used any mods or extensions, please list them here with the version and a link to each mod/extension.

  - type: textarea
    id: bug-description
    attributes:
      label: Issue Description
      description: |
        Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
        You can include images or videos with drag and drop.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        List of steps that reproduces the issue. Having reproducible issues is a prerequisite for contributors to be able to solve them.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: os
    attributes:
      label: "Operating System"
      description: "Select the Operating System you found the bug under. If you've tested multiple and reproduced the bug, you can select more than one."
      options:
        - label: Windows 11
        - label: macOS
        - label: Linux
