name: 🔢 Build Matrix

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-matrix:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            os: windows-latest
            name: 🏁 Windows Debug
            preset: windows-x64-template_debug
            configuration: Debug

          - identifier: windows-release
            os: windows-latest
            name: 🏁 Windows Release
            preset: windows-x64-template_release
            configuration: Release

          - identifier: windows-editor
            os: windows-latest
            name: 🏁 Windows Editor
            preset: windows-x64-editor
            configuration: RelWithDebInfo

          - identifier: macos-debug
            os: macos-latest
            name: 🍎 macOS (universal) Debug
            preset: macos-universal-template_debug
            configuration: Debug

          - identifier: macos-release
            os: macos-latest
            name: 🍎 macOS (universal) Release
            preset: macos-universal-template_release
            configuration: Release

          - identifier: macos-editor
            os: macos-latest
            name: 🍎 macOS (universal) Editor
            preset: macos-universal-editor
            configuration: RelWithDebInfo

          - identifier: linux-debug
            os: ubuntu-22.04
            name: 🐧 Linux Debug
            preset: linux-x64-template_debug
            configuration: Debug

          - identifier: linux-release
            os: ubuntu-22.04
            name: 🐧 Linux Release
            preset: linux-x64-template_release
            configuration: Release

          - identifier: linux-editor
            os: ubuntu-22.04
            name: 🐧 Linux Editor
            preset: linux-x64-editor
            configuration: RelWithDebInfo

    steps:
      - name: Checkout project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/openvic-build
        with:
          identifier: ${{ matrix.identifier }}
          preset: ${{ matrix.preset }}
          configuration: ${{ matrix.configuration }}
